# Generated by Django 4.0.3 on 2022-04-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_alter_vehicle_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='customer',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='customer',
            field=models.ManyToManyField(related_name='Vehicle', to='orm.customer'),
        ),
    ]
